"use client";
import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/header/header";
import Footer from "./components/layout/footer/footer";
import { NextUIProvider } from "@nextui-org/react";
import { usePathname } from "next/navigation";
import HeaderAdmin from "./components/admin/header/admin-header";
// import { useRouter } from "next/navigation";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

const metadata: Metadata = {
  title: "eduxLL",
  //description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const path = usePathname();

  return (
    <html lang="en">
      <body className={poppins.className}>
        {path === "/admin/dashboard" || path==="/admin/courses" || path==="/admin/blogs" || path==="/admin/courses/create-course" || path=== "/admin/not-found" ? (
          <div className="flex gap-4 p-6">
            <HeaderAdmin />
            <div>{children}</div>
          </div>
        ) : (
          <>
            <Header />
            <div>{children}</div>
            <Footer />
          </>
        )}
      </body>
    </html>
  );
}
